### ISSUE TITLE
error when speaking 

### ISSUE THREAD

**Issue by TheShoes** [aws-samples/amazon-polly-metahumans#19] opened 2022-09-13 19:55 UTC
Any idea why i get this error on start 
LogPollyMsg: Error: Polly failed to generate audio file. Error: Invalid DNS Label found in URI host
LogPollyMsg: Error: Failed to start speech. GenerateSpeech must be invoked before StartSpeech.

also get it when i type a message in the box and click speak

**Comment by Krxtopher** [comment] 2022-09-13 21:25
The second error can probably be ignored. I think it is caused by the first error. But as for the first error, I'm not sure what would cause that, but here are some things to check...

- Log into the AWS console and navigate to the Polly console. See if you can successfully use the in-browser speech generation UI. If that works...
- Confirm that the AWS config credentials and default region you have set locally (where you MetaHuman project is) match the credentials and region you used when directly triggering Polly from the AWS console.

**Comment by TheShoes** [comment] 2022-09-13 22:14
yeah my credentials had changed and i guess you have to make a new build with the correct credentials?  either way I got it working.  thank you for checking in.

any thoughts on tying in aws lex to this?

**Comment by Krxtopher** [comment] 2022-11-29 15:49
Closing this thread since the original issue has been resolved. Regarding Lex, the current version of this sample project doesn't include Lex but it does include the whole AWS SDK, so you can write your own C++ code to call the Lex API. You can use the Polly code included in this project as a reference for how to call AWS SDK APIs from UE code. Documentation for the [C++ LexRuntimeV2Client can be found here](https://sdk.amazonaws.com/cpp/api/LATEST/class_aws_1_1_lex_runtime_v2_1_1_lex_runtime_v2_client.html).

**Closed by Krxtopher** 2022-11-29 15:49 UTC
